import type { Metadata } from "next";

import "./globals.css";
import { ConvexClientProvider } from "@/components/provider/convex-provider";
import { Toaster } from "sonner";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body>
        <ConvexClientProvider>
        <Toaster position="bottom-center" />

          {children}
        </ConvexClientProvider>
      </body>

    </html>
  );
}
